INSERT INTO jobberland_countries (`id`, `loc`, `code`, `var_name`, `name`, `enabled`) VALUES
(3, 'AF', 'BF', 'burkina-faso', 'Burkina Faso', 'Y'),
(5, 'AF', 'CM', 'cameroon', 'Cameroon', 'Y'),
(6, 'AF', 'CV', 'cape-verde', 'Cape Verde', 'Y'),
(7, 'AF', 'CF', 'central-african-republic', 'Central African Republic', 'Y'),
(8, 'AF', 'TD', 'chad', 'Chad', 'Y'),
(9, 'AF', 'KM', 'comoros', 'Comoros', 'Y'),
(10, 'AF', 'CG', 'congo', 'Congo', 'Y'),
(12, 'AF', 'BJ', 'benin', 'Benin', 'Y'),
(14, 'AF', 'BI', 'burundi', 'Burundi', 'Y'),
(21, 'AF', 'CI', 'cote-d-ivorie', 'Cote D''Ivorie', 'Y'),
(22, 'AF', 'DJ', 'djibouti', 'Djibouti', 'Y'),
(23, 'AF', 'GQ', 'equatorial-guinea', 'Equatorial Guinea', 'Y'),
(24, 'AF', 'ER', 'eritrea', 'Eritrea', 'Y'),
(25, 'AF', 'ET', 'ethiopia', 'Ethiopia', 'Y'),
(26, 'AF', 'EG', 'egypt', 'Egypt', 'Y'),
(27, 'AF', 'GA', 'gabon', 'Gabon', 'Y'),
(28, 'AF', 'GH', 'ghana', 'Ghana', 'Y'),
(29, 'AF', 'GN', 'guinea', 'Guinea', 'Y'),
(30, 'AF', 'GM', 'gambia', 'Gambia', 'Y'),
(31, 'AF', 'GW', 'guinea-bissau', 'Guinea-Bissau', 'Y'),
(32, 'AF', 'KE', 'kenya', 'Kenya', 'Y'),
(33, 'AF', 'LS', 'lesotho', 'Lesotho', 'Y'),
(34, 'AF', 'LR', 'liberia', 'Liberia', 'Y'),
(35, 'AF', 'MG', 'madagascar', 'Madagascar', 'Y'),
(36, 'AF', 'ML', 'mali', 'Mali', 'Y'),
(37, 'AF', 'MR', 'mauritania', 'Mauritania', 'Y'),
(38, 'AF', 'YT', 'mayotte', 'Mayotte', 'Y'),
(39, 'AF', 'MA', 'morocco', 'Morocco', 'Y'),
(40, 'AF', 'MZ', 'mozambique', 'Mozambique', 'Y'),
(41, 'AF', 'MW', 'malawi', 'Malawi', 'Y'),
(42, 'AF', 'NA', 'namibia', 'Namibia', 'Y'),
(43, 'AF', 'NE', 'niger', 'Niger', 'Y'),
(44, 'AF', 'NG', 'nigeria', 'Nigeria', 'Y'),
(45, 'AF', 'RE', 'reunion', 'Reunion', 'Y'),
(46, 'AF', 'SH', 'st-helena', 'St. Helena', 'Y'),
(47, 'AF', 'ST', 'sao-tome-and-principe', 'Sao Tome and Principe', 'Y'),
(48, 'AF', 'SN', 'senegal', 'Senegal', 'Y'),
(49, 'AF', 'SL', 'sierra-leone', 'Sierra Leone', 'Y'),
(50, 'AF', 'SO', 'somalia', 'Somalia', 'Y'),
(51, 'AF', 'ZA', 'south-africa', 'South Africa', 'Y'),
(52, 'AF', 'SD', 'sudan', 'Sudan', 'Y'),
(53, 'AF', 'SZ', 'swaziland', 'Swaziland', 'Y'),
(54, 'AF', 'TZ', 'tanzania', 'Tanzania', 'Y'),
(55, 'AF', 'TG', 'togo', 'Togo', 'Y'),
(56, 'AF', 'UG', 'uganda', 'Uganda', 'Y'),
(57, 'AF', 'EH', 'western-sahara', 'Western Sahara', 'Y'),
(58, 'AF', 'ZR', 'zaire', 'Zaire', 'Y'),
(59, 'AF', 'ZM', 'zambia', 'Zambia', 'Y'),
(60, 'AF', 'ZW', 'zimbabwe', 'Zimbabwe', 'Y'),
(62, 'AS', 'AF', 'afghanistan', 'Afghanistan', 'Y'),
(63, 'AS', 'BD', 'bangladesh', 'Bangladesh', 'Y'),
(64, 'AS', 'BT', 'bhutan', 'Bhutan', 'Y'),
(65, 'AS', 'BN', 'brunei', 'Brunei', 'Y'),
(66, 'AS', 'KH', 'cambodia', 'Cambodia', 'Y'),
(67, 'AS', 'CN', 'china', 'China', 'Y'),
(68, 'AS', 'HK', 'hong-kong', 'Hong Kong', 'Y'),
(69, 'AS', 'IN', 'india', 'India', 'Y'),
(70, 'AS', 'ID', 'indonesia', 'Indonesia', 'Y'),
(71, 'AS', 'JP', 'japan', 'Japan', 'Y'),
(72, 'AS', 'KZ', 'kazakhstan', 'Kazakhstan', 'Y'),
(73, 'AS', 'KG', 'kyrgyzstan', 'Kyrgyzstan', 'Y'),
(74, 'AS', 'LA', 'laos', 'Laos', 'Y'),
(75, 'AS', 'MO', 'macau', 'Macau', 'Y'),
(76, 'AS', 'MY', 'malaysia', 'Malaysia', 'Y'),
(77, 'AS', 'MV', 'maldives', 'Maldives', 'Y'),
(78, 'AS', 'MN', 'mongolia', 'Mongolia', 'Y'),
(79, 'AS', 'NP', 'nepal', 'Nepal', 'Y'),
(80, 'AS', 'PK', 'pakistan', 'Pakistan', 'Y'),
(81, 'AS', 'PH', 'philippines', 'Philippines', 'Y'),
(82, 'AS', 'KR', 'republic-of-korea', 'Republic of Korea', 'Y'),
(83, 'AS', 'RU', 'russia', 'Russia', 'Y'),
(84, 'AS', 'SC', 'seychelles', 'Seychelles', 'Y'),
(85, 'AS', 'SG', 'singapore', 'Singapore', 'Y'),
(86, 'AS', 'LK', 'sri-lanka', 'Sri Lanka', 'Y'),
(87, 'AS', 'TW', 'taiwan', 'Taiwan', 'Y'),
(88, 'AS', 'TJ', 'tajikistan', 'Tajikistan', 'Y'),
(89, 'AS', 'TH', 'thailand', 'Thailand', 'Y'),
(90, 'AS', 'TM', 'turkmenistan', 'Turkmenistan', 'Y'),
(91, 'AS', 'UZ', 'uzbekistan', 'Uzbekistan', 'Y'),
(92, 'AS', 'VN', 'vietnam', 'Vietnam', 'Y'),
(94, 'AU', 'AU', 'australia', 'Australia', 'Y'),
(95, 'AU', 'FM', 'federated-states-of-micronesia', 'Federated States of Micronesia', 'Y'),
(96, 'AU', 'FJ', 'fiji', 'Fiji', 'Y'),
(97, 'AU', 'PF', 'french-polynesia', 'French Polynesia', 'Y'),
(98, 'AU', 'GU', 'guam', 'Guam', 'Y'),
(99, 'AU', 'KI', 'kiribati', 'Kiribati', 'Y'),
(100, 'AU', 'MH', 'marshall-islands', 'Marshall Islands', 'Y'),
(101, 'AU', 'NR', 'nauru', 'Nauru', 'Y'),
(102, 'AU', 'NC', 'new-caledonia', 'New Caledonia', 'Y'),
(103, 'AU', 'NZ', 'new-zealand', 'New Zealand', 'Y'),
(104, 'AU', 'MP', 'northern-mariana-islands', 'Northern Mariana Islands', 'Y'),
(105, 'AU', 'PW', 'palau', 'Palau', 'Y'),
(106, 'AU', 'PG', 'papua-new-guinea', 'Papua New Guinea', 'Y'),
(107, 'AU', 'PN', 'pitcairn', 'Pitcairn', 'Y'),
(108, 'AU', 'SB', 'solomon-islands', 'Solomon Islands', 'Y'),
(109, 'AU', 'TO', 'tonga', 'Tonga', 'Y'),
(110, 'AU', 'TV', 'tuvalu', 'Tuvalu', 'Y'),
(111, 'AU', 'VU', 'vanuatu', 'Vanuatu', 'Y'),
(112, 'CA', 'AI', 'anguilla', 'Anguilla', 'Y'),
(114, 'CA', 'AW', 'aruba', 'Aruba', 'Y'),
(115, 'CA', 'BS', 'bahamas', 'Bahamas', 'Y'),
(116, 'CA', 'BB', 'barbados', 'Barbados', 'Y'),
(117, 'CA', 'BM', 'bermuda', 'Bermuda', 'Y'),
(118, 'CA', 'VI', 'british-virgin-islands', 'British Virgin Islands', 'Y'),
(119, 'CA', 'KY', 'cayman-islands', 'Cayman Islands', 'Y'),
(120, 'CA', 'DM', 'dominica', 'Dominica', 'Y'),
(121, 'CA', 'DO', 'dominican-republic', 'Dominican Republic', 'Y'),
(122, 'CA', 'GD', 'grenada', 'Grenada', 'Y'),
(123, 'CA', 'GP', 'guadeloupe', 'Guadeloupe', 'Y'),
(124, 'CA', 'HT', 'haiti', 'Haiti', 'Y'),
(125, 'CA', 'JM', 'jamaica', 'Jamaica', 'Y'),
(126, 'CA', 'MQ', 'martinique', 'Martinique', 'Y'),
(127, 'CA', 'AN', 'neterlands-antilles', 'Neterlands Antilles', 'Y'),
(128, 'CA', 'PR', 'puerto-rico', 'Puerto Rico', 'Y'),
(129, 'CA', 'KN', 'st-kitts-and-nevis', 'St. Kitts and Nevis', 'Y'),
(130, 'CA', 'LC', 'st-lucia', 'St. Lucia', 'Y'),
(131, 'CA', 'VC', 'st-vincent-and-the-grenadines', 'St. Vincent and the Grenadines', 'Y'),
(132, 'CA', 'TT', 'trinidad-and-tobago', 'Trinidad and Tobago', 'Y'),
(133, 'CA', 'TC', 'turks-and-caicos-islands', 'Turks and Caicos Islands', 'Y'),
(134, 'CE', 'BZ', 'belize', 'Belize', 'Y'),
(135, 'CE', 'CR', 'costa-rica', 'Costa Rica', 'Y'),
(136, 'CE', 'SV', 'el-salvador', 'El Salvador', 'Y'),
(137, 'CE', 'GT', 'guatemala', 'Guatemala', 'Y'),
(138, 'CE', 'HN', 'honduras', 'Honduras', 'Y'),
(139, 'CE', 'NI', 'nicaragua', 'Nicaragua', 'Y'),
(140, 'CE', 'PA', 'panama', 'Panama', 'Y'),
(143, 'CE', 'AM', 'armenia', 'Armenia', 'Y'),
(144, 'CE', 'AT', 'austria', 'Austria', 'Y'),
(145, 'CE', 'AZ', 'azerbaijan', 'Azerbaijan', 'Y'),
(146, 'CE', 'BY', 'belarus', 'Belarus', 'Y'),
(147, 'CE', 'BE', 'belgium', 'Belgium', 'Y'),
(148, 'CE', 'BG', 'bulgaria', 'Bulgaria', 'Y'),
(149, 'CE', 'HR', 'croatia', 'Croatia', 'Y'),
(150, 'CE', 'CY', 'cyprus', 'Cyprus', 'Y'),
(151, 'CE', 'CZ', 'czech-republic', 'Czech Republic', 'Y'),
(152, 'CE', 'DK', 'denmark', 'Denmark', 'Y'),
(153, 'CE', 'EE', 'estonia', 'Estonia', 'Y'),
(154, 'CE', 'FO', 'faroe-islands', 'Faroe Islands', 'Y'),
(155, 'CE', 'FI', 'finland', 'Finland', 'Y'),
(156, 'CE', 'FR', 'france', 'France', 'Y'),
(157, 'CE', 'GE', 'georgia', 'Georgia', 'Y'),
(158, 'CE', 'DE', 'germany', 'Germany', 'Y'),
(159, 'CE', 'GI', 'gibraltar', 'Gibraltar', 'Y'),
(160, 'CE', 'GR', 'greece', 'Greece', 'Y'),
(161, 'CE', 'GL', 'greenland', 'Greenland', 'Y'),
(162, 'CE', 'HU', 'hungary', 'Hungary', 'Y'),
(163, 'CE', 'IS', 'iceland', 'Iceland', 'Y'),
(164, 'CE', 'IE', 'ireland', 'Ireland', 'Y'),
(165, 'CE', 'IT', 'italy', 'Italy', 'Y'),
(166, 'CE', 'LV', 'latvia', 'Latvia', 'Y'),
(167, 'CE', 'LI', 'liechtenstein', 'Liechtenstein', 'Y'),
(168, 'CE', 'LT', 'lithuania', 'Lithuania', 'Y'),
(169, 'CE', 'LU', 'luxembourg', 'Luxembourg', 'Y'),
(170, 'CE', 'MT', 'malta', 'Malta', 'Y'),
(171, 'CE', 'FX', 'metropolitan-france', 'Metropolitan France', 'Y'),
(172, 'CE', 'MD', 'moldova', 'Moldova', 'Y'),
(173, 'CE', 'NL', 'netherlands', 'Netherlands', 'Y'),
(174, 'CE', 'NO', 'norway', 'Norway', 'Y'),
(175, 'CE', 'PL', 'poland', 'Poland', 'Y'),
(176, 'CE', 'PT', 'portugal', 'Portugal', 'Y'),
(177, 'CE', 'RO', 'romania', 'Romania', 'Y'),
(178, 'CE', 'SK', 'slovakia', 'Slovakia', 'Y'),
(179, 'CE', 'SI', 'slovenia', 'Slovenia', 'Y'),
(180, 'CE', 'ES', 'spain', 'Spain', 'Y'),
(181, 'CE', 'SJ', 'svalbard-and-jan-mayen-islands', 'Svalbard and Jan Mayen Islands', 'Y'),
(182, 'CE', 'SE', 'sweden', 'Sweden', 'Y'),
(183, 'CE', 'CH', 'switzerland', 'Switzerland', 'Y'),
(184, 'CE', 'MK', 'republic-of-macedonia', 'Republic of Macedonia', 'Y'),
(185, 'CE', 'TR', 'turkey', 'Turkey', 'Y'),
(186, 'CE', 'UA', 'ukraine', 'Ukraine', 'Y'),
(187, 'CE', 'GB', 'united-kingdom', 'United Kingdom', 'Y'),
(188, 'CE', 'VA', 'vatican-city', 'Vatican City', 'Y'),
(189, 'CE', 'YU', 'yugoslavia', 'Yugoslavia', 'Y'),
(190, 'ME', 'IL', 'israel', 'Israel', 'Y'),
(191, 'ME', 'JO', 'jordan', 'Jordan', 'Y'),
(192, 'ME', 'KW', 'kuwait', 'Kuwait', 'Y'),
(193, 'ME', 'LB', 'lebanon', 'Lebanon', 'Y'),
(194, 'ME', 'OM', 'oman', 'Oman', 'Y'),
(195, 'ME', 'QA', 'qatar', 'Qatar', 'Y'),
(196, 'ME', 'SA', 'saudi-arabia', 'Saudi Arabia', 'Y'),
(197, 'ME', 'SY', 'syria', 'Syria', 'Y'),
(198, 'ME', 'AE', 'united-arab-emirates', 'United Arab Emirates', 'Y'),
(199, 'ME', 'YE', 'yemen', 'Yemen', 'Y'),
(200, 'NA', 'CA', 'canada', 'Canada', 'Y'),
(201, 'NA', 'MX', 'mexico', 'Mexico', 'Y'),
(202, 'NA', 'US', 'united-states', 'United States', 'Y'),
(204, 'SA', 'BO', 'bolivia', 'Bolivia', 'Y'),
(205, 'SA', 'BR', 'brazil', 'Brazil', 'Y'),
(206, 'SA', 'CL', 'chile', 'Chile', 'Y'),
(207, 'SA', 'CO', 'colombia', 'Colombia', 'Y'),
(208, 'SA', 'EC', 'equador', 'Equador', 'Y'),
(209, 'SA', 'FK', 'falkland-islands', 'Falkland Islands', 'Y'),
(210, 'SA', 'GF', 'french-guiana', 'French Guiana', 'Y'),
(211, 'SA', 'GY', 'guyana', 'Guyana', 'Y'),
(212, 'SA', 'PY', 'paraguay', 'Paraguay', 'Y'),
(213, 'SA', 'PE', 'peru', 'Peru', 'Y'),
(214, 'SA', 'SR', 'suriname', 'Suriname', 'Y'),
(215, 'SA', 'UY', 'uruguay', 'Uruguay', 'Y'),
(216, 'SA', 'VE', 'venezuela', 'Venezuela', 'Y'),
(217, 'OT', 'BH', 'bahrain', 'Bahrain', 'Y'),
(218, 'OT', 'BV', 'bouvet-islands', 'Bouvet Islands', 'Y'),
(219, 'OT', 'IO', 'british-indian-ocean-territory', 'British Indian Ocean Territory', 'Y'),
(220, 'AA', 'AA', 'all-countries', 'All Countries', 'Y');
